name: Build and Test Convert Utility

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y gcc-multilib

      - name: Build convert release version
        run: gcc -o convert conversion.c cmdLineInterpreter.c main.c

      - name: Build ctest version with coverage
        run: gcc -o ctest --coverage conversion.c cmdLineInterpreter.c main.c

      - name: Upload convert binary
        uses: actions/upload-artifact@v4
        with:
          name: convert
          path: ./convert
      - name: Ctest artifact
	uses: actions/upload-artifact@v4
	with:
	  name: ctest
	  path: ./ctest
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y gcc-multilib

      - name: Compile test version with coverage and run tests
        run: |
          make ctest; 
          chmod +x ./test_script.sh; 
          ./test_script.sh > test_results.txt

      - name: Generate coverage reports
        run: |
          make ctest; 
          ./test_script.sh > test_results.txt; 
          gcov ctest-conversion.c; 
          gcov ctest-cmdLineInterpreter.c; 
          gcov ctest-main.c
        continue-on-error: true  # Ensures workflow continues if gcov fails on any file

      - name: Upload test results and coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test_artifacts
          path: |
            test_results.txt
            *.gcov
            *.gcda
            *.gcno


