name: Build and Test Convert Utility

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc gcov
      - name: Build convert release version
        run: gcc -o convert conversion.c cmdLineInterpreter.c main.c 
      - name: Upload convert binary
        uses: actions/upload-artifact@v4
        with:
          name: convert
          path: ./convert

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get install -y gcc-multilib
      - name: Compile test version with coverage and run tests
        run: |
          gcc -o convert --coverage conversion.c cmdLineInterpreter.c main.c  # Compile with coverage
          chmod +x ./test_script.sh
          ./test_script.sh > test_results.txt
          gcov conversion.c
          gcov cmdLineInterpreter.c
          gcov main.c
      - name: Upload test results and coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test_artifacts
          path: |
            test_results.txt
            *.gcov
            *.gcda
            *.gcno

